version: "3.8"
services:
  gateway-svc:
    build:
      context: ./GatewayService
      dockerfile: Dockerfile

    container_name: gateway-svc

    environment:
      - SERVICE_URL_DEFAULT_ZONE_DISCOVERY=${SERVICE_URL_DEFAULT_ZONE_DISCOVERY}

    ports:
      - ${SERVER_PORT_GATEWAY}:${SERVER_PORT_GATEWAY}

    networks:
      - default


  discovery-svc:
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile

    container_name: discovery-svc
    environment:
      - SERVER_PORT=${SERVER_PORT_DISCOVERY}
      - SERVER_PORT_DISCOVERY=${SERVER_PORT_DISCOVERY}
      - SERVICE_URL_DEFAULT_ZONE_DISCOVERY=${SERVICE_URL_DEFAULT_ZONE_DISCOVERY}
      - REGISTER_WITH_EUREKA_DISCOVERY=${REGISTER_WITH_EUREKA_DISCOVERY}
      - FETCH_REGISTRY_DISCOVERY=${FETCH_REGISTRY_DISCOVERY}
      - JAVA_TOOL_OPTIONS=--add-opens=java.base/jdk.internal.platform=ALL-UNNAMED
      - JAVA_TOOL_OPTIONS="-XX:-UseContainerSupport"

    ports:
      - ${SERVER_PORT_DISCOVERY}:${SERVER_PORT_DISCOVERY}


    healthcheck:
      test: "curl --fail --silent ${SERVICE_DISCOVERY_HEALTH_CHECK} | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - default


  resource-db:
    image: postgres:alpine
    container_name: resource-svc-db
    volumes:
#      - была проблема с подключением к базе при старте контейнера, типа такой базы нету...при нулевом страте - все работало
      - resource-db-data:/var/lib/postgresql/data
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_RESOURCE_DATABASE_NAME}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME_RESOURCE}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  resource-svc:
    build:
      context: ./ResourceService
      dockerfile: Dockerfile

    depends_on:
      discovery-svc:
        condition: service_healthy
      resource-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio-storage:
        condition: service_healthy

    networks:
      - default


    environment:
      - SERVER_PORT=${SERVER_PORT_RESOURCE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_RESOURCE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_RESOURCE}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_RESOURCE}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME_RESOURCE}
      - SPRING_DATASOURCE_RESOURCE_DIALECT=${SPRING_DATASOURCE_RESOURCE_DIALECT}
      - SPRING_JPA_HIBERNATE_DDL_AUTO_RESOURCE=${SPRING_JPA_HIBERNATE_DDL_AUTO_RESOURCE}
      - SPRING_JPA_SHOW_SQL_RESOURCE=${SPRING_JPA_SHOW_SQL_RESOURCE}
      - SERVICE_URL_DEFAULT_ZONE_DISCOVERY=${SERVICE_URL_DEFAULT_ZONE_DISCOVERY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - MINIO_SERVER_HOST=${MINIO_SERVER_HOST}
      - MINIO_SERVER_BUCKET_NAME=${MINIO_SERVER_BUCKET_NAME}
    ports:
      - ${SERVER_PORT_RESOURCE}:${SERVER_PORT_RESOURCE}

  song-db:
    image: postgres:alpine
    container_name: song-svc-db
    volumes:
      - song-db-data:/var/lib/postgresql/data
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_SONG_DATABASE_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  song-svc:
    build:
      context: ./SongService
      dockerfile: Dockerfile

    depends_on:
      discovery-svc:
        condition: service_healthy
      song-db:
        condition: service_healthy

    environment:
      - SERVER_PORT=${SERVER_PORT_SONG}
      - SPRING_DATASOURCE_URL_SONG=${SPRING_DATASOURCE_URL_SONG}
      - SPRING_DATASOURCE_USERNAME_SONG=${SPRING_DATASOURCE_USERNAME_SONG}
      - SPRING_DATASOURCE_PASSWORD_SONG=${SPRING_DATASOURCE_PASSWORD_SONG}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME_SONG=${SPRING_DATASOURCE_DRIVER_CLASS_NAME_SONG}
      - SPRING_DATASOURCE_SONG_DIALECT=${SPRING_DATASOURCE_SONG_DIALECT}
      - SPRING_JPA_HIBERNATE_DDL_AUTO_SONG=${SPRING_JPA_HIBERNATE_DDL_AUTO_SONG}
      - SPRING_JPA_SHOW_SQL_SONG=${SPRING_JPA_SHOW_SQL_SONG}
      - SERVICE_URL_DEFAULT_ZONE_DISCOVERY=${SERVICE_URL_DEFAULT_ZONE_DISCOVERY}
    ports:
      - ${SERVER_PORT_SONG_SCALE}:${SERVER_PORT_SONG}

    networks:
      - default

#    deploy:
#      replicas: 2


  resource-processor-svc:
    build:
      context: ./ResourceProcessor
      dockerfile: Dockerfile

    depends_on:
      rabbitmq:
        condition: service_healthy
      minio-storage:
        condition: service_healthy

    environment:
      - SERVER_PORT=8181
      - SERVICE_URL_DEFAULT_ZONE_DISCOVERY=${SERVICE_URL_DEFAULT_ZONE_DISCOVERY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - MINIO_SERVER_HOST=${MINIO_SERVER_HOST}
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - ${SERVER_PORT_RESOURCE_PROCESSOR}:${SERVER_PORT_RESOURCE_PROCESSOR}

    networks:
      - default



  minio-storage:
    image: minio/minio
    ports:
      - ${MINIO_SERVER_PORT}:${MINIO_SERVER_PORT}

    environment:
      MINIO_ROOT_USER: ${MINIO_SERVER_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SERVER_SECRET_KEY}
      MINIO_HEALTH_CHECK_HOST: ${MINIO_HEALTH_CHECK_HOST}
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

    healthcheck:
      test: "curl --fail --silent ${MINIO_HEALTH_CHECK_HOST} || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - default


  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_PORT_HTTP}:${RABBITMQ_PORT_HTTP}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default


volumes:
  resource-db-data:
  song-db-data:
  minio_data:

networks:
  default:
    driver: bridge

